"""Generate dependency-free TypeScript contracts from packaged JSON Schemas."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def ts(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return " | ".join("(" + ts(part) + ")" for part in schema[union])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({**schema, "type": value}) for value in kind)
    if kind == "array":
        return "(" + ts(schema.get("items", {})) + ")[]"
    if kind == "object":
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        members = [
            json.dumps(key) + ("" if key in required else "?") + ": " + ts(value) + ";"
            for key, value in properties.items()
        ]
        additional = schema.get("additionalProperties", True)
        if additional is not False:
            members.append(
                "[key: string]: "
                + (ts(additional) if isinstance(additional, dict) else "unknown")
                + ";"
            )
        return "{ " + " ".join(members) + " }"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def generate():
    canonical = json.loads(
        (ROOT / "backend/src/laip/contracts/laip.schema.json").read_text()
    )
    current = json.loads(
        (ROOT / "backend/src/laip/contracts/0.2.0/laip.schema.json").read_text()
    )

    def version_refs(value, prefix):
        if isinstance(value, dict):
            return {
                key: item.replace("#/$defs/", "#/$defs/" + prefix)
                if key == "$ref"
                else version_refs(item, prefix)
                for key, item in value.items()
            }
        if isinstance(value, list):
            return [version_refs(item, prefix) for item in value]
        return value

    definitions = {}
    for prefix, source in (("V010", canonical), ("V020", current)):
        definitions.update(
            {
                prefix + key: version_refs(value, prefix)
                for key, value in source["$defs"].items()
            }
        )
    for name in sorted(canonical["$defs"].keys() | current["$defs"].keys()):
        alternatives = [
            {"$ref": "#/$defs/" + prefix + name}
            for prefix, source in (("V010", canonical), ("V020", current))
            if name in source["$defs"]
        ]
        definitions[name] = {"oneOf": alternatives}
    # These analyst projection shapes are schema-backed and intentionally keep extensible diagnostic records.
    item = {"type": "object"}
    arr = {"type": "array", "items": item}
    workspace = {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "namespace",
            "snapshot_id",
            "imports",
            "runs",
            "exports",
            "ai_enabled",
            "limitations",
        ],
        "properties": {
            "namespace": {"type": "string"},
            "snapshot_id": {"type": ["string", "null"]},
            "imports": arr,
            "runs": arr,
            "exports": arr,
            "ai_enabled": {"const": False},
            "supported_schema_versions": {
                "type": "array",
                "items": {"enum": ["0.1.0", "0.2.0"]},
            },
            "limitations": {"type": "array", "items": {"type": "string"}},
        },
    }
    read = json.loads((ROOT / "docs/contracts/0.2.0/read-tools.json").read_text())
    definitions["AnalystWorkspace"] = workspace
    definitions["ReadBundle"] = read["operations"]["entity"]["output_schema"][
        "properties"
    ]["data"]
    definitions["SourceWindow"] = {
        "type": "object",
        "required": ["artifact_id", "text", "origin_map_id", "range", "limitations"],
        "properties": {
            "artifact_id": {"type": "string"},
            "text": {"type": "string"},
            "origin_map_id": {"type": "string"},
            "range": {
                "type": "object",
                "required": ["start_line", "end_line"],
                "properties": {
                    "start_line": {"type": "integer"},
                    "end_line": {"type": "integer"},
                },
            },
            "limitations": {"type": "array", "items": {"type": "string"}},
        },
    }
    declarations = [
        "// Generated by scripts/generate_api_types.py. Do not edit by hand.",
        'export type SchemaVersion = "0.1.0" | "0.2.0";',
    ]
    for name, schema in definitions.items():
        declarations.append("export type " + name + " = " + ts(schema) + ";")
    target = ROOT / "web/src/lib/generated-api.ts"
    output = "\n".join(declarations) + "\n"
    if "--check" in __import__("sys").argv:
        if not target.exists() or target.read_text() != output:
            raise SystemExit("Generated API types are stale")
    else:
        target.write_text(output)
    print("Backend schema TypeScript contracts are current.")


if __name__ == "__main__":
    generate()
